"""Rebalance-based portfolio backtest for stock-pool selections."""
from typing import Dict

import pandas as pd


class SelectionBacktester:
    """Backtest target holdings generated by stock-pool selection."""

    def __init__(self, initial_cash: float = 100000.0, commission_rate: float = 0.0003, slippage: float = 0.0):
        self.initial_cash = initial_cash
        self.commission_rate = commission_rate
        self.slippage = slippage

    def run(self, prices: pd.DataFrame, holdings: pd.DataFrame) -> Dict[str, pd.DataFrame]:
        """Run a daily portfolio backtest using next-day returns after rebalance."""
        if prices.empty or holdings.empty:
            empty = pd.DataFrame(columns=["trade_date", "daily_return", "portfolio_value"])
            return {"daily_returns": empty, "rebalance_trades": pd.DataFrame()}

        price_panel = self._prepare_returns(prices)
        dates = sorted(price_panel.index)
        holdings_by_date = self._holdings_by_rebalance(holdings)
        current_weights: Dict[str, float] = {}
        pending_weights: Dict[str, float] | None = None
        last_weights: Dict[str, float] = {}
        portfolio_value = self.initial_cash
        daily_rows = []
        trade_rows = []

        for current_date in dates:
            if current_date in holdings_by_date:
                pending_weights = holdings_by_date[current_date]
                turnover = self._turnover(last_weights, pending_weights)
                cost = turnover * (self.commission_rate + self.slippage)
                trade_rows.append({
                    "rebalance_date": current_date,
                    "turnover": turnover,
                    "cost_rate": cost,
                })

            if pending_weights is not None and current_date > min(holdings_by_date.keys()):
                current_weights = pending_weights
                last_weights = dict(current_weights)
                pending_weights = None

            row_returns = price_panel.loc[current_date]
            daily_return = 0.0
            if current_weights:
                for symbol, weight in current_weights.items():
                    value = row_returns.get(symbol, 0.0)
                    daily_return += weight * (0.0 if pd.isna(value) else value)
            portfolio_value *= (1 + daily_return)
            daily_rows.append({
                "trade_date": current_date,
                "daily_return": daily_return,
                "portfolio_value": portfolio_value,
            })

        return {
            "daily_returns": pd.DataFrame(daily_rows),
            "rebalance_trades": pd.DataFrame(trade_rows),
        }

    @staticmethod
    def _prepare_returns(prices: pd.DataFrame) -> pd.DataFrame:
        data = prices.copy()
        data["trade_date"] = pd.to_datetime(data["trade_date"])
        data = data.sort_values(["symbol", "trade_date"])
        data["symbol_return"] = data.groupby("symbol")["close"].pct_change().fillna(0.0)
        return data.pivot(index="trade_date", columns="symbol", values="symbol_return").fillna(0.0)

    @staticmethod
    def _holdings_by_rebalance(holdings: pd.DataFrame) -> Dict[pd.Timestamp, Dict[str, float]]:
        data = holdings.copy()
        data["rebalance_date"] = pd.to_datetime(data["rebalance_date"])
        result = {}
        for rebalance_date, group in data.groupby("rebalance_date", sort=True):
            result[pd.Timestamp(rebalance_date)] = dict(zip(group["symbol"], group["target_weight"]))
        return result

    @staticmethod
    def _turnover(previous: Dict[str, float], current: Dict[str, float]) -> float:
        symbols = set(previous) | set(current)
        return sum(abs(current.get(symbol, 0.0) - previous.get(symbol, 0.0)) for symbol in symbols) / 2
